### ISSUE TITLE
Downloading tweets issue

### ISSUE THREAD

**Issue by Federica-Giua** [DataAccess2020/Capstone-Project-Davi-Giua#1]
Me and @valentinadavi  are trying to download all the italian tweets containing both the hashtags #coronavirus and #fakenews. We are doing so with the rtweet package using the following function:
 tweets_collection <- search_tweets2(
  c("coronavirus , fakenews"), 
  n = 18000, 
  retryonratelimit = TRUE, 
  parse = TRUE,
  include_rts = FALSE,
  lang = "it"
)
Unfortunately, it doesn't work. It loads till 3%-4% and then stops. @DeAngelisA  any idea why is this happening?

Ps: we tried before without some codes (such as "lang" or "parse") or adding them and it worked on and off.

**Comment by DeAngelisA** [comment]
@Federica-Giua @valentinadavi : non posso aiutarvi anche volendo, perché questo issue non ha né l'errore né è riproducibile. [Qui ](https://stackoverflow.com/help/how-to-ask) c'è come chiedere una cosa, e [qui ](https://stackoverflow.com/help/minimal-reproducible-example) come fare un esempio riproducibile. Poi comunque sono andato un attimo su google e digitando: "rtweet search_tweet stops" ho trovato al secondo risultato [questa domanda](https://stackoverflow.com/questions/56653197/downloading-tweets-using-rtweet-package-appears-to-stop-at-8-why) SO: secondo me dovete solo aspettare perché incappate nei limiti di twitter. Fatemi sapere e non venite da me come prima cosa: imparare a trovare da sé le soluzioni è fondamentale, usate questo esercizio per fare pratica. Fatemi sapere!

**Comment by Federica-Giua** [comment]
Il problema è che non c'è nessun errore semplicemente smette di funzionare, di fare il download. Probabilmente riguarda i limiti di Twitter (ci avevamo pensato proprio perché non c'è errore). Grazie comunque! :)

**Comment by valentinadavi** [comment]
Take a look at this: 
https://github.com/ropensci/rtweet/issues/364
from what I got, sometimes it's simply that there aren't enough tweets, so r gets all it can and then it stops without saying anything. I don't know (and I don't know how to find it) if that's our case, with the double keywords, but I've tried repeteadly and I keep finding the same 270 something tweets, so maybe we're being too specific

**Comment by DeAngelisA** [comment]
@valentinadavi : prova a togliere una keyword.
